name: Daily Bot Run

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Also allow manual trigger

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: npm run bot
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      
      - name: Configure Git User
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
      
      - name: Commit and Push changes
        run: |
          git add data/products.json
          git commit -m "Update products.json with latest scraped data" || echo "No changes to commit" # Commit only if there are changes
          git push origin main
        continue-on-error: true # In case of no changes to commit, continue workflow
  
      - name: Archive Scraped Data
        uses: actions/upload-artifact@v4
        with:
          name: product-data
          path: data/products.json
