name: Product Poster Run

on:
  schedule:
    - cron: '30 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Also allow manual trigger

jobs:
  run-poster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Poster
        run: npm run post
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MONGODB_DBNAME: ${{ secrets.MONGODB_DBNAME }}
          MONGODB_COLLNAME: ${{ secrets.MONGODB_COLLNAME }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          BLUESKY_SERVICE_URL: ${{ secrets.BLUESKY_SERVICE_URL }}
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
