name: Daily Scrape

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Also allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        run: npm run scrape   # Assuming you have a script "scrape" in package.json

      - name: Archive Scraped Data
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: path/to/output.json  # or .md file containing the scraped markdown
